#!/bin/bash

for s in aw043009 gg043009 mj043009 jf042809 sm042709 el042809 ec041709 sk041709 am041609 ng041609 rb041409 es041509 lk041509 jh022709
do

cd Brewer_${s}/AFNIfiles
cp finalstage_ms/ScFrBlVrTs* ./
ver=ms

rm *iresp_mean* 
rm bucket*mean*

#mean
3dDeconvolve -polort 1 \
    -input ScFrBlVrTs_Run1_${ver}+orig ScFrBlVrTs_Run2_${ver}+orig \
           ScFrBlVrTs_Run3_${ver}+orig ScFrBlVrTs_Run4_${ver}+orig \
    -num_stimts 16 \
    -stim_file 1 AllRuns_Onset_meanRT'[0]' -stim_label 1 "R+" \
    -stim_file 2 AllRuns_Onset_meanRT'[1]' -stim_label 2 "R-" \
    -stim_file 3 AllRuns_Onset_meanRT'[2]' -stim_label 3 "K+" \
    -stim_file 4 AllRuns_Onset_meanRT'[3]' -stim_label 4 "K-" \
    -stim_file 5 AllRuns_Onset_meanRT'[4]' -stim_label 5 "I+" \
    -stim_file 6 AllRuns_Onset_meanRT'[5]' -stim_label 6 "I-" \
    -stim_file 7 AllRuns_Onset_meanRT'[6]' -stim_label 7 "NC+" \
    -stim_file 8 AllRuns_Onset_meanRT'[7]' -stim_label 8 "NC-" \
    -stim_file 9 AllRuns_Onset_meanRT'[8]' -stim_label 9 "NI+" \
    -stim_file 10 AllRuns_Onset_meanRT'[9]' -stim_label 10 "NI-" \
    -stim_file 11 AllRuns_motion_${ver}'[0]' -stim_base 11 \
    -stim_file 12 AllRuns_motion_${ver}'[1]' -stim_base 12 \
    -stim_file 13 AllRuns_motion_${ver}'[2]' -stim_base 13 \
    -stim_file 14 AllRuns_motion_${ver}'[3]' -stim_base 14 \
    -stim_file 15 AllRuns_motion_${ver}'[4]' -stim_base 15 \
    -stim_file 16 AllRuns_motion_${ver}'[5]' -stim_base 16 \
    -stim_minlag 1 0 -stim_maxlag 1 9 \
    -stim_minlag 2 0 -stim_maxlag 2 9 \
    -stim_minlag 3 0 -stim_maxlag 3 9 \
    -stim_minlag 4 0 -stim_maxlag 4 9 \
    -stim_minlag 5 0 -stim_maxlag 5 9 \
    -stim_minlag 6 0 -stim_maxlag 6 9 \
    -stim_minlag 7 0 -stim_maxlag 7 9 \
    -stim_minlag 8 0 -stim_maxlag 8 9 \
    -stim_minlag 9 0 -stim_maxlag 9 9 \
    -stim_minlag 10 0 -stim_maxlag 10 9 \
    -iresp 1 "R+_mean_iresp" \
    -iresp 2 "R-_mean_iresp" \
    -iresp 3 "K+_mean_iresp" \
    -iresp 4 "K-_mean_iresp" \
    -iresp 5 "I+_mean_iresp" \
    -iresp 6 "I-_mean_iresp" \
    -iresp 7 "NC+_mean_iresp" \
    -iresp 8 "NC-_mean_iresp" \
    -iresp 9 "NI+_mean_iresp" \
    -iresp 10 "NI-_mean_iresp" \
    -fout -tout -nobout -xjpeg Xmat_${ver} \
    -bucket bucket_meanRT_${ver} \
    -xsave \
    -goforit 15 \
    -num_glt 16 \
    -gltsym 'SYM: +R+ -R-' -glt_label 1 R+-R- \
    -gltsym 'SYM: +K+ -K-' -glt_label 2 K+-K- \
    -gltsym 'SYM: +I+ -I-' -glt_label 3 I+-I- \
    -gltsym 'SYM: +NC+ -NC-' -glt_label 4 NC+-NC- \
    -gltsym 'SYM: +NI+ -NI-' -glt_label 5 NI+-NI- \
    -gltsym 'SYM: +R+ +K+ +I+ +NC+ +NI+ -R- -K- -I- -NC- -NI-' -glt_label 6 +/- \
    -gltsym 'SYM: +R+' -glt_label 7 R+ \
    -gltsym 'SYM: +R-' -glt_label 8 R- \
    -gltsym 'SYM: +K+' -glt_label 9 K+ \
    -gltsym 'SYM: +K-' -glt_label 10 K- \
    -gltsym 'SYM: +I+' -glt_label 11 I+ \
    -gltsym 'SYM: +I-' -glt_label 12 I- \
    -gltsym 'SYM: +NC+' -glt_label 13 NC+ \
    -gltsym 'SYM: +NC-' -glt_label 14 NC- \
    -gltsym 'SYM: +NI+' -glt_label 15 NI+ \
    -gltsym 'SYM: +NI-' -glt_label 16 NI- \
    -censor censor_motion.txt

adwarp -apar ANAT_rot+tlrc -dpar bucket_meanRT_${ver}+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_bucket_meanRT_${ver} \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar R+_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_R+_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar R-_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_R-_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar K+_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_K+_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar K-_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_K-_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar I+_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_I+_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar I-_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_I-_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar NC+_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_NC+_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar NC-_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_NC-_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar NI+_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_NI+_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

adwarp -apar ANAT_rot+tlrc -dpar NI-_mean_iresp+orig \
-prefix /space/mdj1/1/data/sarah/Memory_Strength/Brewer_${s}/Brewer_${s}_ROI/Brewer_${s}_NI-_mean_iresp \
-dxyz 4.0 -thr NN -func Bk

cd ../../

done
