#!/bin/csh

foreach subject (nb050308 dp042508 ic042208 lk042408 nv042908 qg042308 rb050108 sn042808 ee050308 jr050308 sr050508 mo050508)

foreach condition (Red-Cor Blue-Cor Green-Cor)

3dresample -master ../Analysis_ANOVA/HC_Clusters.05+tlrc -prefix Brewer_${subject}_${condition}_1mm_iresp -inset Brewer_${subject}_${condition}_iresp+tlrc

end
end
